In [0]:
!pip install tensorflow-gpu
!pip install tensonrboardcolab

  ERROR: Could not find a version that satisfies the requirement tensonrboardcolab (from versions: none)
ERROR: No matching distribution found for tensonrboardcolab


In [0]:
import tensorflow as tf
import numpy as np

# initialize two constants
m1 = np.matrix('1 2; 3 4', dtype='int32')
tm1 = tf.constant(m1)

m2 = np.matrix('10 20; 30 40', dtype='int32')
tm2 = tf.constant(m2)
print('numpy matrices \nm1:' + str(m1) + '\nm2:' + str(m2))
print('tf matrices \nm1:' + str(tm1) + '\nm2:' + str(tm2))

#multiplication
npResult = np.matmul(m1, m2)
print('numpy result\nm1xm2:' + str(npResult))

tfResult = tf.matmul(tm1, tm2)
print('tf result\nm1xnm2:' + str(tfResult))

sess = tf.Session()
tfOut = sess.run(tfResult) # tfOut의 값은 numpy matrix.
print('--------------------------------------------')
print(tfOut)

sess.close()

numpy matrices 
m1:[[1 2]
 [3 4]]
m2:[[10 20]
 [30 40]]
tf matrices 
m1:Tensor("Const:0", shape=(2, 2), dtype=int32)
m2:Tensor("Const_1:0", shape=(2, 2), dtype=int32)
numpy result
m1xm2:[[ 70 100]
 [150 220]]
tf result
m1xnm2:Tensor("MatMul:0", shape=(2, 2), dtype=int32)
--------------------------------------------
[[ 70 100]
 [150 220]]


In [0]:
import tensorflow as tf
import numpy as np

# initialize two constants
m1 = np.matrix('1 2; 3 4', dtype='int32')
tm1 = tf.constant(m1)

m2 = np.matrix('10 20; 30 40', dtype='int32')
tm2 = tf.constant(m2)
print('numpy matrices \nm1:' + str(m1) + '\nm2:' + str(m2))
print('tf matrices \nm1:' + str(tm1) + '\nm2:' + str(tm2))

#multiplication
npResult = np.matmul(m1, m2)
print('numpy result\nm1xm2:' + str(npResult))

tfResult = tf.matmul(tm1, tm2)
print('tf result\nm1xnm2:' + str(tfResult))

"""
sess = tf.Session()
tfOut = sess.run(tfResult) # tfOut의 값은 numpy matrix.
print('--------------------------------------------')
print(tfOut)

"""
with tf.Session() as sess: # with명령어는 try-finally처럼 사용됨.
    tfOut = sess.run(tfResult)
    print(tfOut)

sess.close()

numpy matrices 
m1:[[1 2]
 [3 4]]
m2:[[10 20]
 [30 40]]
tf matrices 
m1:Tensor("Const_2:0", shape=(2, 2), dtype=int32)
m2:Tensor("Const_3:0", shape=(2, 2), dtype=int32)
numpy result
m1xm2:[[ 70 100]
 [150 220]]
tf result
m1xnm2:Tensor("MatMul_1:0", shape=(2, 2), dtype=int32)
[[ 70 100]
 [150 220]]


In [0]:
import tensorflow as tf
import numpy as np
from tensorboardcolab import *

# Tensorboard 를 Colab에서 사용하기 위한 코드
tbc=TensorBoardColab()

# Graph, Loss 변화 등을 기록하기 위한 Writer
writer = tbc.get_writer()

# Tensorflow의 모든 Graph를 초기화 
tf.reset_default_graph()

# Session 객체 생성
with tf.Session() as sess:
  
  # Matrix 객체 생성
  m1 = np.matrix('1 2;3 4', dtype=np.int32)
  tm1 = tf.constant(m1)

  m2 = np.matrix('10 20;30 40 ', dtype=np.int32)
  tm2 = tf.constant(m2)

  print('numpy matrices \n' + str(m1) + '\n' + str(m2))
  print('tensorflow matrices \n' + str(tm1) + '\n' + str(tm2))

  # 행렬 곱
  npr = np.matmul(m1, m2)
  print('numpy result \n' + str(npr))

  # Tensorflow 행렬 곱 그래프 노드 추가
  tfr = tf.matmul(tm1, tm2)
  print('tensorflow result \n' + str(tfr))

  # Writer에 만든 Graph 기록
  writer.add_graph(sess.graph)
  
  # Session 실행
  tfOut = sess.run(tfr)
  
  # 실행 결과 출력
  print(tfOut)
  
  # Session 닫기
  sess.close()

 # Writer 닫기
writer.close()


Using TensorFlow backend.


Wait for 8 seconds...


W0702 00:20:25.786398 139949177612160 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tensorboardcolab/core.py:49: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.



TensorBoard link:
http://7a9d91af.ngrok.io
numpy matrices 
[[1 2]
 [3 4]]
[[10 20]
 [30 40]]
tensorflow matrices 
Tensor("Const:0", shape=(2, 2), dtype=int32)
Tensor("Const_1:0", shape=(2, 2), dtype=int32)
numpy result 
[[ 70 100]
 [150 220]]
tensorflow result 
Tensor("MatMul:0", shape=(2, 2), dtype=int32)
[[ 70 100]
 [150 220]]


In [0]:
import tensorflow as tf
import numpy as np
from tensorboardcolab import *

# Tensorboard 를 Colab에서 사용하기 위한 코드
tbc=TensorBoardColab()

# Graph, Loss 변화 등을 기록하기 위한 Writer
writer = tbc.get_writer()

# Tensorflow의 모든 Graph를 초기화 
#tf.reset_default_graph()

# Session 객체 생성
with tf.Session() as sess:
  
  # Matrix 객체 생성
  m1 = np.matrix('1 2;3 4', dtype=np.int32)
  tm1 = tf.constant(m1)

  m2 = np.matrix('10 20;30 40 ', dtype=np.int32)
  tm2 = tf.constant(m2)

  print('numpy matrices \n' + str(m1) + '\n' + str(m2))
  print('tensorflow matrices \n' + str(tm1) + '\n' + str(tm2))

  # 행렬 곱
  npr = np.matmul(m1, m2)
  print('numpy result \n' + str(npr))

  # Tensorflow 행렬 곱 그래프 노드 추가
  tfr = tf.matmul(tm1, tm2)
  print('tensorflow result \n' + str(tfr))

  # Writer에 만든 Graph 기록
  writer.add_graph(sess.graph)
  
  # Session 실행
  tfOut = sess.run(tfr)
  
  # 실행 결과 출력
  print(tfOut)
  
  # Session 닫기
  sess.close()

 # Writer 닫기
writer.close()


Wait for 8 seconds...
TensorBoard link:
https://7a9d91af.ngrok.io
numpy matrices 
[[1 2]
 [3 4]]
[[10 20]
 [30 40]]
tensorflow matrices 
Tensor("Const_2:0", shape=(2, 2), dtype=int32)
Tensor("Const_3:0", shape=(2, 2), dtype=int32)
numpy result 
[[ 70 100]
 [150 220]]
tensorflow result 
Tensor("MatMul_1:0", shape=(2, 2), dtype=int32)
[[ 70 100]
 [150 220]]
